// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, created_at, updated_at, email)
VALUES (gen_random_uuid(), NOW(), NOW(), $1)
`

func (q *Queries) CreateUser(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, createUser, email)
	return err
}
